import SideBar from "@/components/dashboard-user/sideBar/SideBar";
import { fetchUserServer } from "@/lib/fetchUserServer";
import UserProvider from "@/providers/UserProvider";
import { Metadata } from "next";
import React from "react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
export const dynamic = "force-dynamic";
export const metadata: Metadata = {
  title: "لوحة التحكم",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await fetchUserServer();
  console.log("currnet user", user);

  // if (!user) {
  //   redirect("/login");
  // }

  return (
    <>
      <div className="flex gap-4  h-screen bg-white dark:bg-bodyDark">
        <SideBar />
        <ToastContainer />
        <main className="flex-1  ">
          <UserProvider user={user}>{children}</UserProvider>
        </main>
      </div>
    </>
  );
}
