import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "الرئيسية",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl" className="dark">
      <body className={` antialiased dark:bg-bodyDark dark:text-white `}>
        {children}
      </body>
    </html>
  );
}
